// Script to find missing neighbourhoods
const dbNeighbourhoods = [
  "ADMIRALTY", "AIRPORT ROAD", "ALEXANDRA HILL", "ALEXANDRA NORTH", "ALJUNIED", "ANAK BUKIT", "ANCHORVALE",
  "ANG MO KIO TOWN CENTRE", "ANSON", "BAHAR", "BALESTIER", "BANGKIT", "BAYFRONT SUBZONE", "BAYSHORE",
  "BEDOK NORTH", "BEDOK RESERVOIR", "BEDOK SOUTH", "BENCOOLEN", "BENDEMEER", "BENOI SECTOR", "BIDADARI",
  "BISHAN EAST", "BOAT QUAY", "BOON KENG", "BOON LAY PLACE", "BOON TECK", "BOULEVARD", "BRADDELL",
  "BRAS BASAH", "BRICKLAND", "BRICKWORKS", "BUGIS", "BUKIT BATOK CENTRAL", "BUKIT BATOK EAST",
  "BUKIT BATOK SOUTH", "BUKIT BATOK WEST", "BUKIT HO SWEE", "BUKIT MERAH", "CAIRNHILL", "CECIL",
  "CENTRAL SUBZONE", "CENTRAL WATER CATCHMENT", "CHANGI AIRPORT", "CHANGI BAY", "CHANGI POINT",
  "CHANGI WEST", "CHATSWORTH", "CHENG SAN", "CHIN BEE", "CHINA SQUARE", "CHINATOWN",
  "CHOA CHU KANG CENTRAL", "CHOA CHU KANG NORTH", "CHONG BOON", "CITY HALL", "CITY TERMINALS",
  "CLARKE QUAY", "CLEANTECH", "CLEMENTI CENTRAL", "CLEMENTI NORTH", "CLEMENTI WEST", "CLEMENTI WOODS",
  "CLIFFORD PIER", "COMMONWEALTH", "COMPASSVALE", "CONEY ISLAND", "CORONATION ROAD", "CRAWFORD",
  "DAIRY FARM", "DEFU INDUSTRIAL PARK", "DEPOT ROAD", "DHOBY GHAUT", "DOVER", "DUNEARN",
  "EAST COAST", "EVERTON PARK", "FABER", "FAJAR", "FARRER COURT", "FARRER PARK", "FERNVALE",
  "FLORA DRIVE", "FOREST HILL", "FORT CANNING", "FRANKEL", "GALI BATU", "GARDEN", "GEYLANG BAHRU",
  "GEYLANG EAST", "GHIM MOH", "GOMBAK", "GOODWOOD PARK", "GREENWOOD PARK", "GUILIN", "GUL BASIN",
  "GUL CIRCLE", "HENDERSON HILL", "HILLCREST", "HILLVIEW", "HOLLAND DRIVE", "HOLLAND ROAD",
  "HONG KAH", "HONG KAH NORTH", "HOUGANG CENTRAL", "HOUGANG EAST", "HOUGANG WEST",
  "INSTITUTION HILL", "INTERNATIONAL BUSINESS PARK", "ISTANA NEGARA", "JELEBU", "JOO KOON",
  "JOO SENG", "JURONG GATEWAY", "JURONG ISLAND AND BUKOM", "JURONG PORT", "JURONG RIVER",
  "JURONG WEST CENTRAL", "KAKI BUKIT", "KALLANG BAHRU", "KALLANG WAY", "KAMPONG BUGIS",
  "KAMPONG GLAM", "KAMPONG JAVA", "KAMPONG TIONG BAHRU", "KAMPONG UBI", "KANGKAR", "KATONG",
  "KEAT HONG", "KEBUN BAHRU", "KEMBANGAN", "KENT RIDGE", "KHATIB", "KIAN TECK", "KIM KEAT",
  "KOVAN", "KRANJI", "LAKESIDE (BUSINESS)", "LAKESIDE (LEISURE)", "LAVENDER", "LEEDON PARK",
  "LEONIE HILL", "LIM CHU KANG", "LITTLE INDIA", "LIU FANG", "LORONG 8 TOA PAYOH",
  "LORONG AH SOO", "LORONG CHUAN", "LORONG HALUS", "LORONG HALUS NORTH", "LOWER SELETAR",
  "LOYANG EAST", "LOYANG WEST", "MACKENZIE", "MACPHERSON", "MALCOLM", "MANDAI EAST",
  "MANDAI ESTATE", "MANDAI WEST", "MARGARET DRIVE", "MARINA CENTRE", "MARINA EAST",
  "MARINA EAST (MP)", "MARINA SOUTH", "MARINE PARADE", "MARITIME SQUARE", "MARYMOUNT",
  "MATILDA", "MAXWELL", "MEI CHIN", "MIDVIEW", "MONK'S HILL", "MOULMEIN", "MOUNT EMILY",
  "MOUNT PLEASANT", "MOUNTBATTEN", "MURAI", "NASSIM", "NATIONAL UNIVERSITY OF S'PORE",
  "NATURE RESERVE", "NEE SOON", "NEWTON CIRCUS", "NICOLL", "NORTH COAST",
  "NORTH-EASTERN ISLANDS", "NORTHLAND", "NORTHSHORE", "ONE NORTH", "ONE TREE HILL",
  "ORANGE GROVE", "OXLEY", "PANDAN", "PANG SUA", "PARK", "PASIR PANJANG 1",
  "PASIR PANJANG 2", "PASIR RIS CENTRAL", "PASIR RIS DRIVE", "PASIR RIS PARK",
  "PASIR RIS WAFER FAB PARK", "PASIR RIS WEST", "PATERSON", "PAYA LEBAR EAST",
  "PAYA LEBAR NORTH", "PAYA LEBAR WEST", "PEARL'S HILL", "PEI CHUN", "PENG SIANG",
  "PENJURU CRESCENT", "PEOPLE'S PARK", "PHILLIP", "PIONEER SECTOR", "PLAB", "PLANTATION",
  "PORT", "POTONG PASIR", "PULAU PUNGGOL BARAT", "PULAU PUNGGOL TIMOR", "PULAU SELETAR",
  "PUNGGOL CANAL", "PUNGGOL FIELD", "PUNGGOL TOWN CENTRE", "QUEENSWAY", "RAFFLES PLACE",
  "REDHILL", "RESERVOIR VIEW", "RIDOUT", "RIVERVALE", "ROBERTSON QUAY", "ROCHOR CANAL",
  "SAFTI", "SAMULUN", "SAUJANA", "SELEGIE", "SELETAR", "SELETAR AEROSPACE PARK",
  "SELETAR HILLS", "SEMAKAU", "SEMBAWANG CENTRAL", "SEMBAWANG EAST", "SEMBAWANG HILLS",
  "SEMBAWANG NORTH", "SEMBAWANG SPRINGS", "SEMBAWANG STRAITS", "SENGKANG TOWN CENTRE",
  "SENGKANG WEST", "SENJA", "SENNETT", "SENOKO NORTH", "SENOKO SOUTH", "SENOKO WEST",
  "SENTOSA", "SERANGOON CENTRAL", "SERANGOON GARDEN", "SERANGOON NORTH",
  "SERANGOON NORTH IND ESTATE", "SHANGRI-LA", "SHIPYARD", "SIGLAP", "SIMEI",
  "SIMPANG NORTH", "SIMPANG SOUTH", "SINGAPORE GENERAL HOSPITAL", "SINGAPORE POLYTECHNIC",
  "SOMERSET", "SOUTHERN GROUP", "SPRINGLEAF", "STRAITS VIEW", "SUDONG", "SUNGEI ROAD",
  "SUNSET WAY", "SWISS CLUB", "TAGORE", "TAI SENG", "TAMAN JURONG", "TAMPINES EAST",
  "TAMPINES NORTH", "TAMPINES WEST", "TANGLIN", "TANGLIN HALT", "TANJONG IRAU",
  "TANJONG PAGAR", "TANJONG RHU", "TEBAN GARDENS", "TECK WHYE", "TELOK BLANGAH DRIVE",
  "TELOK BLANGAH RISE", "TELOK BLANGAH WAY", "TENGAH INDUSTRIAL ESTATE", "TENGEH",
  "THE WHARVES", "TIONG BAHRU", "TIONG BAHRU STATION", "TOA PAYOH CENTRAL", "TOA PAYOH WEST",
  "TOH GUAN", "TOH TUCK", "TOWNSVILLE", "TRAFALGAR", "TUAS BAY", "TUAS NORTH",
  "TUAS PROMENADE", "TUAS VIEW", "TUAS VIEW EXTENSION", "TUKANG", "TURF CLUB", "TYERSALL",
  "ULU PANDAN", "UPPER PAYA LEBAR", "UPPER THOMSON", "VICTORIA", "WATERWAY EAST", "WENYA",
  "WEST COAST", "WOODGROVE", "WOODLANDS EAST", "WOODLANDS REGIONAL CENTRE", "WOODLANDS SOUTH",
  "WOODLANDS WEST", "WOODLEIGH", "XILIN", "YEW TEE", "YIO CHU KANG", "YIO CHU KANG EAST",
  "YIO CHU KANG NORTH", "YIO CHU KANG WEST", "YISHUN CENTRAL", "YISHUN EAST", "YISHUN SOUTH",
  "YISHUN WEST", "YUHUA EAST", "YUHUA WEST", "YUNNAN"
];

// Read existing neighbourhoods from file
const fs = require('fs');
const existing = fs.readFileSync('/tmp/existing_neighbourhoods.txt', 'utf8')
  .split('\n')
  .filter(Boolean)
  .map(n => n.toUpperCase());

const missing = dbNeighbourhoods.filter(n => {
  const normalized = n.toUpperCase();
  // Check exact match
  if (existing.includes(normalized)) return false;
  // Check if any existing contains this name or vice versa
  return !existing.some(e => e.includes(normalized) || normalized.includes(e));
});

console.log(`Total in DB: ${dbNeighbourhoods.length}`);
console.log(`Total existing: ${existing.length}`);
console.log(`Missing: ${missing.length}`);
console.log('\nMissing neighbourhoods:');
missing.forEach(n => console.log(n));

